VS 2019 Refresh
* Setup Azure DevOps for CI
  * Install Android NDK Bundle on Windows build agents
  * Workaround for `JAVA_HOME` on Windows build agents
* Support for Android NDK r19 and r20
* Updated Cake scripts to support VS 2019 on Windows
* Pin NuGet download URL to v4.7.3
* Bump to xamarin/xamarin-android-tools/master@294f447
  * Changes: https://github.com/xamarin/xamarin-android-tools/compare/4c00c22...294f447
* Fix for `mono-support.h` on Windows

Fixes:

    c:\program files (x86)\mono\include\mono-2.0\mono\utils\mono-publib.h(94): error C2371: 'mono_unichar2': redefinition; different basic types [D:\a\1\s\tests\common\mk\common.Tests.vcxproj]